datadog.apiKey: unset

stripe.apiKey: unset
stripe.idempotencyKeyGenerator: abcdefg12345678= # base64 for creating request idempotency hash

braintree.privateKey: unset

directoryV2.client.userAuthenticationTokenSharedSecret: abcdefghijklmnopqrstuvwxyz0123456789ABCDEFG= # base64-encoded secret shared with CDS to generate auth tokens for Signal users
directoryV2.client.userIdTokenSharedSecret: bbcdefghijklmnopqrstuvwxyz0123456789ABCDEFG= # base64-encoded secret shared with CDS to generate auth identity tokens for Signal users

svr2.userAuthenticationTokenSharedSecret: abcdefghijklmnopqrstuvwxyz0123456789ABCDEFG= # base64-encoded secret shared with SVR2 to generate auth tokens for Signal users
svr2.userIdTokenSharedSecret: bbcdefghijklmnopqrstuvwxyz0123456789ABCDEFG= # base64-encoded secret shared with SVR2 to generate auth identity tokens for Signal users

svr3.userAuthenticationTokenSharedSecret: cbcdefghijklmnopqrstuvwxyz0123456789ABCDEFG= # base64-encoded secret shared with SVR3 to generate auth tokens for Signal users
svr3.userIdTokenSharedSecret: dbcdefghijklmnopqrstuvwxyz0123456789ABCDEFG= # base64-encoded secret shared with SVR3 to generate auth identity tokens for Signal users

tus.userAuthenticationTokenSharedSecret: abcdefghijklmnopqrstuvwxyz0123456789ABCDEFG=

awsAttachments.accessKey: test
awsAttachments.accessSecret: test

gcpAttachments.rsaSigningKey: |
  -----BEGIN PRIVATE KEY-----
  MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDMMh9ciJIVIKAV
  ZpYB1zttmAc1zIJof1MmdG8othqDl9FUEEDCJdkbDqywmvMAS1/Um/0EzMAWRF2q
  30fG9iCZl0K1ouAUjrCLzcFgDiI433KLpgPqPkgc2HRmpso+EgAXy/r+ngYXw5JO
  95Kq8j2EzgT8Q2zL7kZRZJb0BAe++A+QZc/smY05cveVRjGOMlJ3Mm0Keq8hrZRi
  iYerlIsxEBLFEAL55c1rnEs5ND34+yTE/e4hCJx4r1ZTzdR4C6tBGhf5n5yaU9wK
  N3ScdKvuNCxYIePOLX+S2aV/BAt1dAjnDAxRWxhQHAI0nbqtYbe0tNVMVE6hrKg4
  DCUojfFFAgMBAAECggEAK2u9H4ArEDMP130pCNsr1/IsFlSWpoHsvJCl0pJmsPTn
  nmiWXLKPqCFGt4c7hSSCDEPfWdXwQsvm3x77tGNCK2bu2JD59WUiRZhLNpHK1S0u
  vmNfEcCMtRWSKwHsn6ZUPrsxdFNGGGeOBRzAI3m/ey4UAVCVIghZC5XIQ7tXqlPU
  PgqiL1B7K7gr83vnOhteV8dfdKVP84O44Aae0AKUaufuS3Q+UcNPB5Jbp5iavLwf
  M+Tt6bjldp+5Xtv4WNlCGvwkxmp5HYNiRUnbcwTHZpdnwL1H3XEXKRqm26AYQ9D2
  qZPwg9WVg4FclcltaQJm9AvKGwrYwtg9LwPq8fG4AQKBgQDmYsOzXvdX4V1N2Bwd
  KQEgY2X1CNnJKlV5s5kM11m4ZsJJFdOD16SQrPLAyNaFJE7HRdv9xhMTGfCwpfVz
  UQoktNQJTDrl5EXrn88J31T5x+sI50wgvngre2FmVo86Mgq503iRd7+Jatk7n57E
  I/Wfp5uKmwxn1xIKfHNvHgvbpQKBgQDi5fBJ7WalGgHUb7huhEyrHM4ZcFjN/zZe
  zYQL5riJps6lw8OEm5yhW5ZghSfkhqjpsZwsofYjry6hAKGUNH8et84k98SJ46zz
  fUohUUC3hmr4Few8QFVteZqirg9YZHRJASiaczaS1+iKyTPPG4Bf8SBhMs5x2wt6
  n6eEjj5NIQKBgGymKTrfT3CPZMxAXcnWu6RFnCC6AtNe9p6Fd2lZ6gMP2xJSi8TC
  nuZn2bfXP2vc2pYZuQzuK7K3ag40xhOTJWB4MwMLgz9Frz/WxvIV8+I0SQCS7BEJ
  Im0HK8Dyk2tTjEFknJily5uH21jGBz7i4oRfq/fq9SfHgseVN28w0VDNAoGBAJqk
  syf/uNTQK+0ZE++nFgYNxN6Ltsr3pZvpoJTn9GBFI1TRXyGzWYaUQKKaPn0/1kIo
  vlOhM3xQuowbPQUg3n8WMVb606ZTWZ4+h1a75UrwP1nEv1S1WEQb/GviDC1nkeXr
  9zuFSO2+YAyvYzNGADHjyvjUQuZQr7sss2Th+c5hAoGBAJzkHdecjANKHn3+a5iO
  5oI+Qh+QB5zUkl+nDyb6TxmI/KbWmpW0Xw6UU6hG3QNkc9d1MOGd20swYTdgrWEA
  TyNCNq3/LYAvsE6fJFjYv+o0JCqpkD/F/2wiuxyO/rX0GxH+3xjnNX6Q6xZXQiRp
  uRk76URIo2PPOSYfn83aZ85U
  -----END PRIVATE KEY-----

apn.teamId: team-id
apn.keyId: key-id
apn.signingKey: |
  -----BEGIN PRIVATE KEY-----
  MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCBd6GS02oWsHHPZRDmI
  K4owyLme46NVNVisLJSC+cNFFQ==
  -----END PRIVATE KEY-----

fcm.credentials: |
  {
    "type": "service_account",
    "project_id": "zinc-computer-205115",
    "private_key_id": "495bf99fb5cd362023ae45d7e10bee0231543bbf",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCezkj8sFfYZvVA\ntlIsQ2j3+DRpsk7PpFyBIBti3r7MJx4c+LzXXq1y205wXW9OCUicsiagbP8b2i0S\nRQx3WHlUSLD1il8NTl+3gIN+Am25baDZ5zlBno0caVffhCwJiNp0ocQIheSSq6+u\nAe/hdDsgr8BOhZFN4y7UXbazlzj/wQyR92O40njV/my/nQ38wSK8sRUpMGket5hT\naNNq2hsRkQc3Gd7LUa7Xsd/bg9mueC119gPjTx6JZ22p5lX39Oc11+afuoJcWW6f\nUwrvcBM9r6aby8BxuFXI2rhvrmrSSmE4DgAhd2SzpYzLYI4gQ+BQdanDjaQv4zAn\nWKTO23QrAgMBAAECggEACzexxX0Et4SOTm6Sig3jnEssE0tFGzsWTbNhkS+qypZO\nH5MdGRmBpwYBbxkqg5ikSG1NIofl0qcsB95YwxVnfKH7M1z9hIhvZRxELY0pCFrL\nbJj+B7nraIEIdAF3cDT6jsKJK7ue1GghlhO3niACYoyySNmmf0SiSjNUdIXPa5aw\nOTlwWXc3ioBIzjqndV2dneWchLEwC1rGtH/sSyqLn8uDpw63/Ov6RsxERzcul9YT\nX9Go0bzwFFaWA6pN2Q57ohM4Acu5M8qKgkpPSddSRmNZ+YO3PhJafcbbJUlQ5rCR\nkHLtgeWObA3n2RhEbWMnvUHyjr/5fDdIpvtd390OAQKBgQDOLPb7dGnJZkkYRUxk\nvvi3qMk285omDOC9W51HOGj3KiEe2D6Tr5IarX0AVzGkBFxe7DWwLqd5o//CV7AA\nMX+kpbaBiZv75tHD/azQiirdzyv/LrjmRgD/AURjMjY378S5VD+CujtGknBi/98w\n7P56m09kW0+QdJ5/gmmpOVICRwKBgQDFLsozUGCqn1lscwugr+96qY1Wj6rwriTl\n66Gfo5y1njHIFLKlTarUmeseJQO7Uo0HuUBwa8iTbLReXf3rag163Su/8VdttjUu\nDQhaUEJ5ZHhtM/wZxui1cfuXORgBCo0pmmpTjRyK3sGhJlZw8WCK2Jhraiq/AIjY\nQstSjr0s/QKBgQDDEG24aGKx5rFfYikt5DTC5tFAyWddeq+i2CvMt0UwG87sNOG3\nrtPHo75xdQ2FRY7zS/5bqzhOcOhIwdfFxw8iAprSohRPVwm9qaM4RpDZ/Ol+bIEJ\ndM/6dAN06ou7joEMavYPxAzS7zefosBStNbrv0d1BqMXZA6VSxiWv6GkfwKBgQCX\ntLYQ4MhevZbZX3IUwQepAgYiEQrdfb4Zvz5sSj7pZLq8S2Be2fCS/ZDtcmD6oDqt\nNJQlame5NStYZ0xS8RdJ7hwY4x/24vbrZU+F3LYoG2qj6hkN5AFqiDWfVWfodSvC\nVHF1st3A4j1rNMnQv4UdjiNGkTouFcUzTcCM1hEqKQKBgA0egg+7hIXWfdR7dME9\nRaxCy/gWE7eOhzO7EH3nD8raWoRWjg+GJGAonAVedoH+6OBdwBGrLmjpabYBybVs\noy4xWdum+Wh5ntAhqKj1gRhX/jjtiB2vDerFnr0xLpe/0Ic8sgUOi9HToeC79FmY\nIvfZYicvo+7QSQ0KJSsSq/cS\n-----END PRIVATE KEY-----\n",
    "client_email": "signalapp-dev@zinc-computer-205115.iam.gserviceaccount.com",
    "client_id": "113697207441272222105",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/signalapp-dev%40zinc-computer-205115.iam.gserviceaccount.com",
    "universe_domain": "googleapis.com"
  }

cdn.accessKey: test    # AWS Access Key ID
cdn.accessSecret: test # AWS Access Secret

cdn3StorageManager.clientSecret: test

unidentifiedDelivery.certificate: CiUIARIhBSE1Tp+ef8GCMlkAGcH3sOCUCpOHBzBRYQkHlQuzFTdKEkBpw9lGN6yYLleWj4UhSgM3E8/fFqBSP9pB9Kpw0u7+PakGK05kXQoQWggA70id789UPXti/zXcsGTw/VEsdjSP
unidentifiedDelivery.privateKey: WAJxAd173jh/KKYJ4T0pPciWlIUTbl+v7RhwI6Rao2Y=

hCaptcha.apiKey: unset

storageService.userAuthenticationTokenSharedSecret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

zkConfig.serverSecret: 6987b92bdea075d3f8b42b39d780a5be0bc264874a18e11cac694e4fe28f6cca
zkConfig-libsignal-0.36.serverSecret: ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzAA==
zkConfig-libsignal-0.37.serverSecret: ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzAA==

genericZkConfig.serverSecret: ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzAA==
callingZkConfig.serverSecret: ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzAA==
backupsZkConfig.serverSecret: ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyzAA==

paymentsService.userAuthenticationTokenSharedSecret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= # base64-encoded 32-byte secret shared with MobileCoin services used to generate auth tokens for Signal users
paymentsService.fixerApiKey: unset
paymentsService.coinMarketCapApiKey: unset

artService.userAuthenticationTokenSharedSecret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= # base64-encoded 32-byte secret not shared with any external service, but used in ArtController
artService.userAuthenticationTokenUserIdSecret: AAAAAAAAAAA= # base64-encoded secret to obscure user phone numbers from Sticker Creator

currentReportingKey.secret: AAAAAAAAAAA=
currentReportingKey.salt: AAAAAAAAAAA=

turn.secret: AAAAAAAAAAA=

linkDevice.secret: AAAAAAAAAAA=

tlsKeyStore.password: password
